Update vendor [deny-all] (#777)
* Update vendor [deny-all]

* Deny all network policy

diff --git a/vendor/github.com/giantswarm/k8scloudconfig/v_5_0_0/files/conf/k8s-addons b/vendor/github.com/giantswarm/k8scloudconfig/v_5_0_0/files/conf/k8s-addons
--- a/vendor/github.com/giantswarm/k8scloudconfig/v_5_0_0/files/conf/k8s-addons
+++ b/vendor/github.com/giantswarm/k8scloudconfig/v_5_0_0/files/conf/k8s-addons
@@ -141,6 +141,19 @@ do
     sleep 5s
 done
 
+# apply network policies:
+NETWORK_POLICIES_FILE="network_policies.yaml"
+NAMESPACES="kube-system giantswarm"
+for namespace in ${NAMESPACES}; do
+    while
+      /usr/bin/docker run -e KUBECONFIG=${KUBECONFIG} --net=host --rm -v /srv:/srv -v /etc/kubernetes:/etc/kubernetes $KUBECTL apply -f /srv/$NETWORK_POLICIES_FILE -n $namespace
+      [ "$?" -ne "0" ]
+    do
+      echo "failed to apply /srv/$NETWORK_POLICIES_FILE, retrying in 5 sec"
+      sleep 5s
+    done
+done
+
 # apply k8s addons
 MANIFESTS=""
 {{ range .ExtraManifests -}}
