Align files

diff --git a/.github/workflows/zz_generated.create_release_pr.yaml b/.github/workflows/zz_generated.create_release_pr.yaml
--- a/.github/workflows/zz_generated.create_release_pr.yaml
+++ b/.github/workflows/zz_generated.create_release_pr.yaml
@@ -25,40 +25,38 @@ jobs:
     name: Gather facts
     runs-on: ubuntu-18.04
     outputs:
-      unchanged: ${{ steps.get_unchanged.outputs.unchanged }}
-      base: ${{ steps.get_base.outputs.base }}
-      version: ${{ steps.get_version.outputs.version }}
+      base: ${{ steps.gather_facts.outputs.base }}
+      version: ${{ steps.gather_facts.outputs.version }}
     steps:
-      - name: Get base
-        id: get_base
+      - name: Gather facts
+        id: gather_facts
         run: |
-          base="$(echo ${{ github.event.ref }} | cut -d '#' -f 1)"
-          echo "base=\"$base\""
-          echo "::set-output name=base::${base}"
-      - name: Get version
-        id: get_version
-        run: |
-          version="$(echo ${{ github.event.ref }} | cut -d '#' -f 3)"
+          echo "::group::Get facts"
+          head="${{ github.event.ref }}"
+          head="${head#refs/heads/}" # Strip "refs/heads/" prefix.
+          base="$(echo $head | cut -d '#' -f 1)"
+          base="${base#refs/heads/}" # Strip "refs/heads/" prefix.
+          version="$(echo $head | cut -d '#' -f 3)"
           version="${version#v}" # Strip "v" prefix.
-          echo "version=\"$version\""
+          echo "base=\"$base\" head=\"$head\" version=\"$version\""
+          echo "::set-output name=base::${base}"
+          echo "::set-output name=head::${head}"
           echo "::set-output name=version::${version}"
-      - name: Checkout base code
-        uses: actions/checkout@v2
-        with:
-          ref: ${{ steps.get_base.outputs.base }}
-      - name: Get unchanged
-        id: get_unchanged
-        env:
-          sha: ${{ github.sha }}
-        run: |
-          base_head=$(git rev-parse HEAD)
-          echo "base_head=\"$base_head\""
-          unchanged="false"
-          if [[ "$base_head" == "${{ env.sha }}" ]] ; then
-            unchanged="true"
+          echo "::endgroup::"
+          echo "::group::Validate"
+          git init -q
+          git remote add origin ${{ github.event.repository.clone_url }}
+          git fetch -q --depth=1 origin $base
+          git fetch -q --depth=1 origin $head
+          out=$(git rev-list --left-right --count origin/$base...origin/$head)
+          ahead=$(echo $out | awk '{print $2}')
+          behind=$(echo $out | awk '{print $1}')
+          echo "ahead=\"$ahead\" behind=\"$behind\""
+          if [[ $ahead -ne 0 ]] || [[ $behind -ne 0 ]] ; then
+            echo "::error:: Branch $head is $ahead commits ahead and $behind commits behind $base branch. Please recreate the $head branch."
+            exit 1
           fi
-          echo "unchanged=\"$unchanged\""
-          echo "::set-output name=unchanged::${unchanged}"
+          echo "::endgroup::"
   install_architect:
     name: Install architect
     runs-on: ubuntu-18.04
@@ -67,7 +65,7 @@ jobs:
       DIR: "/opt/cache"
       IMAGE: "quay.io/giantswarm/architect"
       IMAGE_PATH: "/usr/bin/architect"
-      VERSION: "1.2.0"
+      VERSION: "2.1.4"
     outputs:
       cache_key: "${{ steps.get_cache_key.outputs.cache_key }}"
     steps:
@@ -100,7 +98,6 @@ jobs:
   create_release_pr:
     name: Create release PR
     runs-on: ubuntu-18.04
-    if: ${{ needs.gather_facts.outputs.unchanged == 'true' }}
     needs:
       - gather_facts
       - install_architect
